/** Mapeo código FIFA → clase flag-icons (https://github.com/lipis/flag-icons) */
const FLAG_CLASS: Record<string, string> = {
  MEX: "fi-mx",
  RSA: "fi-za",
  KOR: "fi-kr",
  CZE: "fi-cz",
  CAN: "fi-ca",
  SUI: "fi-ch",
  QAT: "fi-qa",
  BIH: "fi-ba",
  BRA: "fi-br",
  MAR: "fi-ma",
  HAI: "fi-ht",
  SCO: "fi-gb-sct",
  USA: "fi-us",
  PAR: "fi-py",
  AUS: "fi-au",
  TUR: "fi-tr",
  GER: "fi-de",
  CUW: "fi-cw",
  CIV: "fi-ci",
  ECU: "fi-ec",
  NED: "fi-nl",
  JPN: "fi-jp",
  TUN: "fi-tn",
  SWE: "fi-se",
  BEL: "fi-be",
  EGY: "fi-eg",
  IRN: "fi-ir",
  NZL: "fi-nz",
  ESP: "fi-es",
  CPV: "fi-cv",
  KSA: "fi-sa",
  URU: "fi-uy",
  FRA: "fi-fr",
  SEN: "fi-sn",
  NOR: "fi-no",
  IRQ: "fi-iq",
  ARG: "fi-ar",
  ALG: "fi-dz",
  AUT: "fi-at",
  JOR: "fi-jo",
  POR: "fi-pt",
  UZB: "fi-uz",
  COL: "fi-co",
  COD: "fi-cd",
  ENG: "fi-gb-eng",
  CRO: "fi-hr",
  GHA: "fi-gh",
  PAN: "fi-pa",
};

export function getFlagClass(code: string): string | null {
  return FLAG_CLASS[code] ?? null;
}
