-- Polla Mundialista 2026 — Seed data
-- Ejecutar en Supabase SQL Editor después de schema.sql

DELETE FROM predictions;
DELETE FROM matches;
DELETE FROM teams;

INSERT INTO teams (name, code, flag_emoji, group_name) VALUES
  ('México', 'MEX', '🇲🇽', 'Grupo A'),
  ('Sudáfrica', 'RSA', '🇿🇦', 'Grupo A'),
  ('Corea del Sur', 'KOR', '🇰🇷', 'Grupo A'),
  ('Chequia', 'CZE', '🇨🇿', 'Grupo A'),
  ('Canadá', 'CAN', '🇨🇦', 'Grupo B'),
  ('Suiza', 'SUI', '🇨🇭', 'Grupo B'),
  ('Qatar', 'QAT', '🇶🇦', 'Grupo B'),
  ('Bosnia y Herzegovina', 'BIH', '🇧🇦', 'Grupo B'),
  ('Brasil', 'BRA', '🇧🇷', 'Grupo C'),
  ('Marruecos', 'MAR', '🇲🇦', 'Grupo C'),
  ('Haití', 'HAI', '🇭🇹', 'Grupo C'),
  ('Escocia', 'SCO', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Grupo C'),
  ('Estados Unidos', 'USA', '🇺🇸', 'Grupo D'),
  ('Paraguay', 'PAR', '🇵🇾', 'Grupo D'),
  ('Australia', 'AUS', '🇦🇺', 'Grupo D'),
  ('Turquía', 'TUR', '🇹🇷', 'Grupo D'),
  ('Alemania', 'GER', '🇩🇪', 'Grupo E'),
  ('Curazao', 'CUW', '🇨🇼', 'Grupo E'),
  ('Costa de Marfil', 'CIV', '🇨🇮', 'Grupo E'),
  ('Ecuador', 'ECU', '🇪🇨', 'Grupo E'),
  ('Países Bajos', 'NED', '🇳🇱', 'Grupo F'),
  ('Japón', 'JPN', '🇯🇵', 'Grupo F'),
  ('Túnez', 'TUN', '🇹🇳', 'Grupo F'),
  ('Suecia', 'SWE', '🇸🇪', 'Grupo F'),
  ('Bélgica', 'BEL', '🇧🇪', 'Grupo G'),
  ('Egipto', 'EGY', '🇪🇬', 'Grupo G'),
  ('Irán', 'IRN', '🇮🇷', 'Grupo G'),
  ('Nueva Zelanda', 'NZL', '🇳🇿', 'Grupo G'),
  ('España', 'ESP', '🇪🇸', 'Grupo H'),
  ('Cabo Verde', 'CPV', '🇨🇻', 'Grupo H'),
  ('Arabia Saudita', 'KSA', '🇸🇦', 'Grupo H'),
  ('Uruguay', 'URU', '🇺🇾', 'Grupo H'),
  ('Francia', 'FRA', '🇫🇷', 'Grupo I'),
  ('Senegal', 'SEN', '🇸🇳', 'Grupo I'),
  ('Noruega', 'NOR', '🇳🇴', 'Grupo I'),
  ('Irak', 'IRQ', '🇮🇶', 'Grupo I'),
  ('Argentina', 'ARG', '🇦🇷', 'Grupo J'),
  ('Argelia', 'ALG', '🇩🇿', 'Grupo J'),
  ('Austria', 'AUT', '🇦🇹', 'Grupo J'),
  ('Jordania', 'JOR', '🇯🇴', 'Grupo J'),
  ('Portugal', 'POR', '🇵🇹', 'Grupo K'),
  ('Uzbekistán', 'UZB', '🇺🇿', 'Grupo K'),
  ('Colombia', 'COL', '🇨🇴', 'Grupo K'),
  ('Congo DR', 'COD', '🇨🇩', 'Grupo K'),
  ('Inglaterra', 'ENG', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Grupo L'),
  ('Croacia', 'CRO', '🇭🇷', 'Grupo L'),
  ('Ghana', 'GHA', '🇬🇭', 'Grupo L'),
  ('Panamá', 'PAN', '🇵🇦', 'Grupo L'),
  ('Por definir', 'TBD', '❓', 'Eliminatoria');

INSERT INTO matches (home_team_id, away_team_id, phase, scheduled_at, venue, city, external_id, status) VALUES
  ((SELECT id FROM teams WHERE code='MEX'), (SELECT id FROM teams WHERE code='RSA'), 'group', '2026-06-11T19:00:00Z', 'Estadio Azteca', 'Ciudad de México', 1, 'upcoming'),
  ((SELECT id FROM teams WHERE code='KOR'), (SELECT id FROM teams WHERE code='CZE'), 'group', '2026-06-12T02:00:00Z', 'Estadio Akron', 'Guadalajara', 2, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CAN'), (SELECT id FROM teams WHERE code='BIH'), 'group', '2026-06-12T19:00:00Z', 'BMO Field', 'Toronto', 3, 'upcoming'),
  ((SELECT id FROM teams WHERE code='USA'), (SELECT id FROM teams WHERE code='PAR'), 'group', '2026-06-13T01:00:00Z', 'SoFi Stadium', 'Los Angeles', 4, 'upcoming'),
  ((SELECT id FROM teams WHERE code='HAI'), (SELECT id FROM teams WHERE code='SCO'), 'group', '2026-06-14T01:00:00Z', 'Gillette Stadium', 'Boston', 5, 'upcoming'),
  ((SELECT id FROM teams WHERE code='AUS'), (SELECT id FROM teams WHERE code='TUR'), 'group', '2026-06-13T04:00:00Z', 'BC Place', 'Vancouver', 6, 'upcoming'),
  ((SELECT id FROM teams WHERE code='BRA'), (SELECT id FROM teams WHERE code='MAR'), 'group', '2026-06-14T00:00:00Z', 'MetLife Stadium', 'New York', 7, 'upcoming'),
  ((SELECT id FROM teams WHERE code='QAT'), (SELECT id FROM teams WHERE code='SUI'), 'group', '2026-06-13T19:00:00Z', 'Levi''s Stadium', 'San Francisco', 8, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CIV'), (SELECT id FROM teams WHERE code='ECU'), 'group', '2026-06-14T23:00:00Z', 'Lincoln Financial Field', 'Filadelfia', 9, 'upcoming'),
  ((SELECT id FROM teams WHERE code='GER'), (SELECT id FROM teams WHERE code='CUW'), 'group', '2026-06-14T16:00:00Z', 'NRG Stadium', 'Houston', 10, 'upcoming'),
  ((SELECT id FROM teams WHERE code='NED'), (SELECT id FROM teams WHERE code='JPN'), 'group', '2026-06-14T20:00:00Z', 'AT&T Stadium', 'Dallas', 11, 'upcoming'),
  ((SELECT id FROM teams WHERE code='SWE'), (SELECT id FROM teams WHERE code='TUN'), 'group', '2026-06-15T02:00:00Z', 'Estadio BBVA', 'Monterrey', 12, 'upcoming'),
  ((SELECT id FROM teams WHERE code='KSA'), (SELECT id FROM teams WHERE code='URU'), 'group', '2026-06-15T22:00:00Z', 'Hard Rock Stadium', 'Miami', 13, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ESP'), (SELECT id FROM teams WHERE code='CPV'), 'group', '2026-06-15T16:00:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 14, 'upcoming'),
  ((SELECT id FROM teams WHERE code='IRN'), (SELECT id FROM teams WHERE code='NZL'), 'group', '2026-06-16T01:00:00Z', 'SoFi Stadium', 'Los Angeles', 15, 'upcoming'),
  ((SELECT id FROM teams WHERE code='BEL'), (SELECT id FROM teams WHERE code='EGY'), 'group', '2026-06-15T19:00:00Z', 'Lumen Field', 'Seattle', 16, 'upcoming'),
  ((SELECT id FROM teams WHERE code='FRA'), (SELECT id FROM teams WHERE code='SEN'), 'group', '2026-06-16T19:00:00Z', 'MetLife Stadium', 'New York', 17, 'upcoming'),
  ((SELECT id FROM teams WHERE code='IRQ'), (SELECT id FROM teams WHERE code='NOR'), 'group', '2026-06-16T22:00:00Z', 'Gillette Stadium', 'Boston', 18, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ARG'), (SELECT id FROM teams WHERE code='ALG'), 'group', '2026-06-17T01:00:00Z', 'Arrowhead Stadium', 'Kansas City', 19, 'upcoming'),
  ((SELECT id FROM teams WHERE code='AUT'), (SELECT id FROM teams WHERE code='JOR'), 'group', '2026-06-17T04:00:00Z', 'Levi''s Stadium', 'San Francisco', 20, 'upcoming'),
  ((SELECT id FROM teams WHERE code='GHA'), (SELECT id FROM teams WHERE code='PAN'), 'group', '2026-06-17T23:00:00Z', 'BMO Field', 'Toronto', 21, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ENG'), (SELECT id FROM teams WHERE code='CRO'), 'group', '2026-06-17T20:00:00Z', 'AT&T Stadium', 'Dallas', 22, 'upcoming'),
  ((SELECT id FROM teams WHERE code='POR'), (SELECT id FROM teams WHERE code='COD'), 'group', '2026-06-17T16:00:00Z', 'NRG Stadium', 'Houston', 23, 'upcoming'),
  ((SELECT id FROM teams WHERE code='UZB'), (SELECT id FROM teams WHERE code='COL'), 'group', '2026-06-18T02:00:00Z', 'Estadio Azteca', 'Ciudad de México', 24, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CZE'), (SELECT id FROM teams WHERE code='RSA'), 'group', '2026-06-18T16:00:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 25, 'upcoming'),
  ((SELECT id FROM teams WHERE code='SUI'), (SELECT id FROM teams WHERE code='BIH'), 'group', '2026-06-18T19:00:00Z', 'SoFi Stadium', 'Los Angeles', 26, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CAN'), (SELECT id FROM teams WHERE code='QAT'), 'group', '2026-06-18T22:00:00Z', 'BC Place', 'Vancouver', 27, 'upcoming'),
  ((SELECT id FROM teams WHERE code='MEX'), (SELECT id FROM teams WHERE code='KOR'), 'group', '2026-06-19T01:00:00Z', 'Estadio Akron', 'Guadalajara', 28, 'upcoming'),
  ((SELECT id FROM teams WHERE code='BRA'), (SELECT id FROM teams WHERE code='HAI'), 'group', '2026-06-20T01:00:00Z', 'Lincoln Financial Field', 'Filadelfia', 29, 'upcoming'),
  ((SELECT id FROM teams WHERE code='SCO'), (SELECT id FROM teams WHERE code='MAR'), 'group', '2026-06-19T22:00:00Z', 'Gillette Stadium', 'Boston', 30, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TUR'), (SELECT id FROM teams WHERE code='PAR'), 'group', '2026-06-20T03:00:00Z', 'Levi''s Stadium', 'San Francisco', 31, 'upcoming'),
  ((SELECT id FROM teams WHERE code='USA'), (SELECT id FROM teams WHERE code='AUS'), 'group', '2026-06-19T19:00:00Z', 'Lumen Field', 'Seattle', 32, 'upcoming'),
  ((SELECT id FROM teams WHERE code='GER'), (SELECT id FROM teams WHERE code='CIV'), 'group', '2026-06-20T20:00:00Z', 'BMO Field', 'Toronto', 33, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ECU'), (SELECT id FROM teams WHERE code='CUW'), 'group', '2026-06-21T00:00:00Z', 'Arrowhead Stadium', 'Kansas City', 34, 'upcoming'),
  ((SELECT id FROM teams WHERE code='NED'), (SELECT id FROM teams WHERE code='SWE'), 'group', '2026-06-20T16:00:00Z', 'NRG Stadium', 'Houston', 35, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TUN'), (SELECT id FROM teams WHERE code='JPN'), 'group', '2026-06-21T04:00:00Z', 'Estadio BBVA', 'Monterrey', 36, 'upcoming'),
  ((SELECT id FROM teams WHERE code='URU'), (SELECT id FROM teams WHERE code='CPV'), 'group', '2026-06-21T22:00:00Z', 'Hard Rock Stadium', 'Miami', 37, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ESP'), (SELECT id FROM teams WHERE code='KSA'), 'group', '2026-06-21T16:00:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 38, 'upcoming'),
  ((SELECT id FROM teams WHERE code='BEL'), (SELECT id FROM teams WHERE code='IRN'), 'group', '2026-06-21T19:00:00Z', 'SoFi Stadium', 'Los Angeles', 39, 'upcoming'),
  ((SELECT id FROM teams WHERE code='NZL'), (SELECT id FROM teams WHERE code='EGY'), 'group', '2026-06-22T01:00:00Z', 'BC Place', 'Vancouver', 40, 'upcoming'),
  ((SELECT id FROM teams WHERE code='NOR'), (SELECT id FROM teams WHERE code='SEN'), 'group', '2026-06-23T00:00:00Z', 'MetLife Stadium', 'New York', 41, 'upcoming'),
  ((SELECT id FROM teams WHERE code='FRA'), (SELECT id FROM teams WHERE code='IRQ'), 'group', '2026-06-22T21:00:00Z', 'Lincoln Financial Field', 'Filadelfia', 42, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ARG'), (SELECT id FROM teams WHERE code='AUT'), 'group', '2026-06-22T16:00:00Z', 'AT&T Stadium', 'Dallas', 43, 'upcoming'),
  ((SELECT id FROM teams WHERE code='JOR'), (SELECT id FROM teams WHERE code='ALG'), 'group', '2026-06-23T03:00:00Z', 'Levi''s Stadium', 'San Francisco', 44, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ENG'), (SELECT id FROM teams WHERE code='GHA'), 'group', '2026-06-23T20:00:00Z', 'Gillette Stadium', 'Boston', 45, 'upcoming'),
  ((SELECT id FROM teams WHERE code='PAN'), (SELECT id FROM teams WHERE code='CRO'), 'group', '2026-06-23T23:00:00Z', 'BMO Field', 'Toronto', 46, 'upcoming'),
  ((SELECT id FROM teams WHERE code='POR'), (SELECT id FROM teams WHERE code='UZB'), 'group', '2026-06-23T16:00:00Z', 'NRG Stadium', 'Houston', 47, 'upcoming'),
  ((SELECT id FROM teams WHERE code='COL'), (SELECT id FROM teams WHERE code='COD'), 'group', '2026-06-24T02:00:00Z', 'Estadio Akron', 'Guadalajara', 48, 'upcoming'),
  ((SELECT id FROM teams WHERE code='SCO'), (SELECT id FROM teams WHERE code='BRA'), 'group', '2026-06-24T22:00:00Z', 'Hard Rock Stadium', 'Miami', 49, 'upcoming'),
  ((SELECT id FROM teams WHERE code='MAR'), (SELECT id FROM teams WHERE code='HAI'), 'group', '2026-06-24T22:00:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 50, 'upcoming'),
  ((SELECT id FROM teams WHERE code='SUI'), (SELECT id FROM teams WHERE code='CAN'), 'group', '2026-06-24T19:00:00Z', 'BC Place', 'Vancouver', 51, 'upcoming'),
  ((SELECT id FROM teams WHERE code='BIH'), (SELECT id FROM teams WHERE code='QAT'), 'group', '2026-06-24T19:00:00Z', 'Lumen Field', 'Seattle', 52, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CZE'), (SELECT id FROM teams WHERE code='MEX'), 'group', '2026-06-25T01:00:00Z', 'Estadio Azteca', 'Ciudad de México', 53, 'upcoming'),
  ((SELECT id FROM teams WHERE code='RSA'), (SELECT id FROM teams WHERE code='KOR'), 'group', '2026-06-25T01:00:00Z', 'Estadio BBVA', 'Monterrey', 54, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CUW'), (SELECT id FROM teams WHERE code='CIV'), 'group', '2026-06-25T20:00:00Z', 'Lincoln Financial Field', 'Filadelfia', 55, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ECU'), (SELECT id FROM teams WHERE code='GER'), 'group', '2026-06-25T20:00:00Z', 'MetLife Stadium', 'New York', 56, 'upcoming'),
  ((SELECT id FROM teams WHERE code='JPN'), (SELECT id FROM teams WHERE code='SWE'), 'group', '2026-06-25T22:00:00Z', 'AT&T Stadium', 'Dallas', 57, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TUN'), (SELECT id FROM teams WHERE code='NED'), 'group', '2026-06-25T22:00:00Z', 'Arrowhead Stadium', 'Kansas City', 58, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TUR'), (SELECT id FROM teams WHERE code='USA'), 'group', '2026-06-26T02:00:00Z', 'SoFi Stadium', 'Los Angeles', 59, 'upcoming'),
  ((SELECT id FROM teams WHERE code='PAR'), (SELECT id FROM teams WHERE code='AUS'), 'group', '2026-06-26T02:00:00Z', 'Levi''s Stadium', 'San Francisco', 60, 'upcoming'),
  ((SELECT id FROM teams WHERE code='NOR'), (SELECT id FROM teams WHERE code='FRA'), 'group', '2026-06-26T19:00:00Z', 'Gillette Stadium', 'Boston', 61, 'upcoming'),
  ((SELECT id FROM teams WHERE code='SEN'), (SELECT id FROM teams WHERE code='IRQ'), 'group', '2026-06-26T19:00:00Z', 'BMO Field', 'Toronto', 62, 'upcoming'),
  ((SELECT id FROM teams WHERE code='EGY'), (SELECT id FROM teams WHERE code='IRN'), 'group', '2026-06-27T03:00:00Z', 'Lumen Field', 'Seattle', 63, 'upcoming'),
  ((SELECT id FROM teams WHERE code='NZL'), (SELECT id FROM teams WHERE code='BEL'), 'group', '2026-06-27T03:00:00Z', 'BC Place', 'Vancouver', 64, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CPV'), (SELECT id FROM teams WHERE code='KSA'), 'group', '2026-06-27T00:00:00Z', 'NRG Stadium', 'Houston', 65, 'upcoming'),
  ((SELECT id FROM teams WHERE code='URU'), (SELECT id FROM teams WHERE code='ESP'), 'group', '2026-06-27T00:00:00Z', 'Estadio Akron', 'Guadalajara', 66, 'upcoming'),
  ((SELECT id FROM teams WHERE code='PAN'), (SELECT id FROM teams WHERE code='ENG'), 'group', '2026-06-27T21:00:00Z', 'MetLife Stadium', 'New York', 67, 'upcoming'),
  ((SELECT id FROM teams WHERE code='CRO'), (SELECT id FROM teams WHERE code='GHA'), 'group', '2026-06-27T21:00:00Z', 'Lincoln Financial Field', 'Filadelfia', 68, 'upcoming'),
  ((SELECT id FROM teams WHERE code='ALG'), (SELECT id FROM teams WHERE code='AUT'), 'group', '2026-06-28T02:00:00Z', 'Arrowhead Stadium', 'Kansas City', 69, 'upcoming'),
  ((SELECT id FROM teams WHERE code='JOR'), (SELECT id FROM teams WHERE code='ARG'), 'group', '2026-06-28T02:00:00Z', 'AT&T Stadium', 'Dallas', 70, 'upcoming'),
  ((SELECT id FROM teams WHERE code='COL'), (SELECT id FROM teams WHERE code='POR'), 'group', '2026-06-28T23:30:00Z', 'Hard Rock Stadium', 'Miami', 71, 'upcoming'),
  ((SELECT id FROM teams WHERE code='COD'), (SELECT id FROM teams WHERE code='UZB'), 'group', '2026-06-28T23:30:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 72, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-06-28T19:00:00Z', 'SoFi Stadium', 'Los Angeles', 73, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-06-29T20:30:00Z', 'Gillette Stadium', 'Boston', 74, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-06-30T01:00:00Z', 'Estadio BBVA', 'Monterrey', 75, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-06-29T16:00:00Z', 'NRG Stadium', 'Houston', 76, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-06-30T21:00:00Z', 'MetLife Stadium', 'New York', 77, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-06-30T16:00:00Z', 'AT&T Stadium', 'Dallas', 78, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-01T01:00:00Z', 'Estadio Azteca', 'Ciudad de México', 79, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-01T16:00:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 80, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-02T00:00:00Z', 'Levi''s Stadium', 'San Francisco', 81, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-01T20:00:00Z', 'Lumen Field', 'Seattle', 82, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-02T23:00:00Z', 'BMO Field', 'Toronto', 83, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-02T19:00:00Z', 'SoFi Stadium', 'Los Angeles', 84, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-03T03:00:00Z', 'BC Place', 'Vancouver', 85, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-03T22:00:00Z', 'Hard Rock Stadium', 'Miami', 86, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-04T01:30:00Z', 'Arrowhead Stadium', 'Kansas City', 87, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r32', '2026-07-03T17:00:00Z', 'AT&T Stadium', 'Dallas', 88, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-04T21:00:00Z', 'Lincoln Financial Field', 'Filadelfia', 89, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-04T16:00:00Z', 'NRG Stadium', 'Houston', 90, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-05T20:00:00Z', 'MetLife Stadium', 'New York', 91, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-06T00:00:00Z', 'Estadio Azteca', 'Ciudad de México', 92, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-06T19:00:00Z', 'AT&T Stadium', 'Dallas', 93, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-07T00:00:00Z', 'Lumen Field', 'Seattle', 94, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-07T16:00:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 95, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'r16', '2026-07-07T20:00:00Z', 'BC Place', 'Vancouver', 96, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'qf', '2026-07-09T20:00:00Z', 'Gillette Stadium', 'Boston', 97, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'qf', '2026-07-10T19:00:00Z', 'SoFi Stadium', 'Los Angeles', 98, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'qf', '2026-07-11T21:00:00Z', 'Hard Rock Stadium', 'Miami', 99, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'qf', '2026-07-12T01:00:00Z', 'Arrowhead Stadium', 'Kansas City', 100, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'sf', '2026-07-14T18:00:00Z', 'AT&T Stadium', 'Dallas', 101, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'sf', '2026-07-15T19:00:00Z', 'Mercedes-Benz Stadium', 'Atlanta', 102, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'sf', '2026-07-18T21:00:00Z', 'Hard Rock Stadium', 'Miami', 103, 'upcoming'),
  ((SELECT id FROM teams WHERE code='TBD'), (SELECT id FROM teams WHERE code='TBD'), 'final', '2026-07-19T19:00:00Z', 'MetLife Stadium', 'New York', 104, 'upcoming');
